    function [architectures] = EvaluateGNC(filename)
%EvaluateGNC.m
% This function reads a CSV file generated by OPN with a set of feasible
% architectures and computes cost and performance for each architecture.

% Open CSV file
fid = fopen(filename,'r+');
if fid == -1
    disp(['EvaluateGNC: Error when opening CSV file :' filename]);
    return;
end

% Read CSV file and creates vectors of values for C1,C2,C3,etc. 

C = textscan(fid,'%d%d%d%d%d%d%d%d%d%d%d%d%d%*[^\n]','Headerlines',1,'Delimiter',',');
C1 = C{1};
C2 = C{2};
C3 = C{3};
I1 = C{4};
I2 = C{5};
I3 = C{6};
NC = C{7};
NS = C{8};
S1 = C{9};
S2 = C{10};
S3 = C{11};
Narc = length(C1);
R = 0.000000*ones(Narc,1);
m = zeros(Narc,1);
Nlinks = zeros(Narc,1);

for i = 1:Narc    
    %disp(['Calculating architecture i = ', num2str(i)]);
    Rs = ReliabSensor(NS(i),S1(i),S2(i),S3(i));
    Rc = ReliabComputer(NC(i),C1(i),C2(i),C3(i));
    [I,rI] = ReliabInterc(NS(i),NC(i),I1(i),I2(i),I3(i));
    
    % Calculate Reliability
    R(i,1) = CalcReliability(Rs,Rc,I,rI);
    
    % Calculate Mass
    [m(i,1),Nlinks(i,1)] = CalcMass(NS(i),NC(i),S1(i),S2(i),S3(i),C1(i),C2(i),C3(i),I1(i),I2(i),I3(i));
end

for j = 1:Narc
    architectures(j).m = m(j,1);
    architectures(j).R = R(j,1);
    architectures(j).NS = NS(j,1);
    architectures(j).NC = NC(j,1);
    architectures(j).S1 = S1(j,1);
    architectures(j).S2 = S2(j,1);
    architectures(j).S3 = S3(j,1);
    architectures(j).C1 = C1(j,1);
    architectures(j).C2 = C2(j,1);
    architectures(j).C3 = C3(j,1);
    architectures(j).I1 = I1(j,1);
    architectures(j).I2 = I2(j,1);
    architectures(j).I3 = I3(j,1);
    architectures(j).Nlinks = Nlinks(j,1);
    
end

return
% end of EvaluateGNC.m