    function [GNC_out] = EvaluateGNC2(GNC)
%EvaluateGNC.m
% This function reads a CSV file generated by OPN with a set of feasible
% architectures and computes cost and performance for each architecture.

Narc = length(GNC);
GNC_out(1:Narc) = GNC(1); % Just for initializing size;

for i = 1:Narc    
    %fprintf('Evaluating architecture %d from %d\n', i, Narc);
    % Inputs
    NC      = GNC(i).NC;
    NS      = GNC(i).NS;  
    C1      = GNC(i).computers(1);
    C2      = GNC(i).computers(2);
    C3      = GNC(i).computers(3);
    I1      = GNC(i).Inat(1);
    if NS > 1
        I2      = GNC(i).Inat(2);
    else
        I2 = 0;
    end 
    if NS > 2
        I3      = GNC(i).Inat(3);
    else
        I3 = 0;
    end
    S1      = GNC(i).sensors(1);
    S2      = GNC(i).sensors(2);
    S3      = GNC(i).sensors(3);
    R_SA    = GNC(i).R_SA;
    R_SB    = GNC(i).R_SB;
    R_SC    = GNC(i).R_SC;
    R_CA    = GNC(i).R_CA;
    R_CB    = GNC(i).R_CB;
    R_CC    = GNC(i).R_CC;
    R_I     = GNC(i).R_I0;
    M_SA    = GNC(i).M_SA;
    M_SB    = GNC(i).M_SB;
    M_SC    = GNC(i).M_SC;
    M_CA    = GNC(i).M_CA;
    M_CB    = GNC(i).M_CB;
    M_CC    = GNC(i).M_CC;
    M_I     = GNC(i).M_I0;
    vec_RS  = [R_SA,R_SB,R_SC];
    vec_RC  = [R_CA,R_CB,R_CC];
    vec_MS  = [M_SA,M_SB,M_SC];
    vec_MC  = [M_CA,M_CB,M_CC];    
    % Intermediate calculations
    Rs      = ReliabSensor(NS,S1,S2,S3,vec_RS);
    Rc      = ReliabComputer(NC,C1,C2,C3,vec_RC);
    [I,Ri]  = ReliabInterc(NS,NC,I1,I2,I3,R_I);
    
    % Outputs
    GNC_out(i)      = GNC(i);
    %GNC_out(i).R    = CalcReliability(Rs,Rc,I,rI);
    GNC_out(i).R    = FastRelCalc_new(Rs,Rc,Ri);
    %GNC_out(i).R    = CalcReliability_new(Rs,Rc,Ri);
    GNC_out(i).MTTF    = -1/log(GNC_out(i).R);
    GNC_out(i).N9    = -log10(1-GNC_out(i).R);
    DCP = GNC(i).DissimilarComponentPenalty;
    [GNC_out(i).m,GNC_out(i).Nlinks] = CalcMass(NS,NC,S1,S2,S3,C1,C2,C3,I1,I2,I3,vec_MS,vec_MC,M_I,DCP);
end



return
% end of EvaluateGNC.m